### ISSUE TITLE
I am facing this new issue cant't fix it

### ISSUE THREAD

**Issue by prantikseal** [Skyscanner/backpack-docs#1603]
```
Failed to compile.

./node_modules/@skyscanner/backpack-web/bpk-component-button/src/BpkButton.js
SyntaxError: C:\Users\prantik\Desktop\SkyScanner Internship\my-app\node_modules\@skyscanner\backpack-web\bpk-component-button\src\BpkButton.js: Unexpected token, expected "," (39:7)

  37 |
  38 | import {
> 39 |   type Props as CommonProps,
     |        ^
  40 |   propTypes,
  41 |   defaultProps,
  42 | } from './common-types';
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)    at run.next (<anonymous>)
    at transform.next (<anonymous>)

```

@greenkeeperio-bot

**Comment by olliecurtis** [comment]
Hey @prantikseal 👋

Is this from running the docs site or is it from using Backpack Web npm package in a different app? (Taking a look at the path for where the error is thrown)

If it's the latter you will want to raise this issue over on the repo www.github.com/Skyscanner/backpack 

Looking at it what build tool are you using to run/build your project? As Backpack is not shipped compiled you will need to tell the build to compile Backpack which will vary depending on the tool.

Thanks
Ollie

**Comment by olliecurtis** [comment]
An additional thought to add is I see you are running windows which just as a heads up we don't support/have access to so there maybe issues you encounter that we won't be able to resolve due to the environments we work on here at Skyscanner

**Comment by prantikseal** [comment]
> An additional thought to add is I see you are running windows which just as a heads up we don't support/have access to so there maybe issues you encounter that we won't be able to resolve due to the environments we work on here at Skyscanner

Oh okay, thanks for sharing that

**Comment by prantikseal** [comment]
> Hey @prantikseal 👋
> 
> Is this from running the docs site or is it from using Backpack Web npm package in a different app? (Taking a look at the path for where the error is thrown)
> 
> If it's the latter you will want to raise this issue over on the repo [www.github.com/Skyscanner/backpack](http://www.github.com/Skyscanner/backpack)
> 
> Looking at it what build tool are you using to run/build your project? As Backpack is not shipped compiled you will need to tell the build to compile Backpack which will vary depending on the tool.
> 
> Thanks Ollie
